In [1]:
import pandas as pd
import numpy as np
import os

# INE - Data cleaning

Esta notebook muestra el proceso de limpieza  para cada uno de los indicadores seleccionados de INE a partir de las observaciones vistas en el proceso de inspección de datos. Es importante tener en cuenta que solo se van a limpiar datos, cualquier otro proceso relacionado puramente con EDA (p.ej. detectar y gestionar outliers) no forman parte del contexto de esta notebook.

Se tomarán los datasets "raw" de la carpeta 'data_raw/' y, una vez aplicada la limpieza inicial, se guardará una primera versión transformada de cada dataset en la carpeta 'data_interim/' de donde se leerán los datasets de cada indicador limpios con el fin de transformar, combinar y obtener la versión final de los datasets necesarios para pasos posteriores de este proyecto, los cuales se guardarán en 'data_clean/'.

La versión del dataset guardada en 'data_interim/' será en formato 'parquet' dado que permite guardar los datos con los cambios de tipo de datos aplicados, conservando la nueva estructura mejor que en un CSV.

## **income_inhabitant_0012670**: Gross reported  income per inhabitant (€) by Geographic localization (NUTS - 2024)

In [2]:
income_inhab_df = pd.read_csv(r"../data_raw/income_inhabitant.csv", encoding='utf-8')
income_inhab_df.head(5)

    geocod    geodsg  income
0  11C1804   Cinfães    7696
1  11C1813   Resende    7839
2  1C10211   Odemira    7958
3  11B1712  Valpaços    8100
4  11D1819   Tabuaço    8191

In [3]:
income_inhab_df['geocod'] = income_inhab_df['geocod'].astype('str')
income_inhab_df['geodsg'] = income_inhab_df['geodsg'].astype('str')
income_inhab_df['income'] = income_inhab_df['income'].astype('int64')

income_inhab_df.dtypes

geocod    object
geodsg    object
income     int64
dtype: object

In [4]:
interim_path = r"../data_interim"

os.makedirs(interim_path, exist_ok=True)

income_inhab_df.to_parquet(r"../data_interim/income_inhab.parquet")

## **pop_density_0013189**: Population's density (No./ km²) by Place of residence (NUTS - 2024)

In [5]:
pop_density_df = pd.read_csv(r"../data_raw/pop_density.csv", encoding='utf-8')
pop_density_df.head(5)

    geocod         geodsg  density
0  1500802       Alcoutim      4.3
1  1C20209        Mértola      4.6
2  1950505  Idanha-a-Nova      5.9
3  1C31203           Avis      6.0
4  1C31211       Monforte      6.8

In [6]:
pop_density_df['geocod'] = pop_density_df['geocod'].astype('str')
pop_density_df['geodsg'] = pop_density_df['geodsg'].astype('str')
pop_density_df['density'] = pop_density_df['density'].astype('float')

pop_density_df.dtypes

geocod      object
geodsg      object
density    float64
dtype: object

In [7]:
pop_density_df.to_parquet(r"../data_interim/pop_density.parquet")