In [43]:
import pandas as pd
import numpy as np
import json

# INE datasets inspection

This notebook provides a sequential inspection of datasets selected from INE Portugal, focusing on their structure, data quality, temporal and geographic granularity, value ranges, units, and consistency across datasets.

## **income_inhabitant_0012670**: Gross reported  income per inhabitant (€) by Geographic localization (NUTS - 2024)

In [44]:
with open(r"../data_raw/Income_inhabitant_0012670.json", "r", encoding='utf-8') as file:
    data = json.load(file)

data = data[0]['Dados']['2024'] # Al tener el diccionario en una lista, se accede a ella mediante [0]
data

[{'geocod': '11C1804',
  'geodsg': 'Cinfães',
  'ind_string': '7 696',
  'valor': '7696'},
 {'geocod': '11C1813',
  'geodsg': 'Resende',
  'ind_string': '7 839',
  'valor': '7839'},
 {'geocod': '1C10211',
  'geodsg': 'Odemira',
  'ind_string': '7 958',
  'valor': '7958'},
 {'geocod': '11B1712',
  'geodsg': 'Valpaços',
  'ind_string': '8 100',
  'valor': '8100'},
 {'geocod': '11D1819',
  'geodsg': 'Tabuaço',
  'ind_string': '8 191',
  'valor': '8191'},
 {'geocod': '11B1709',
  'geodsg': 'Ribeira de Pena',
  'ind_string': '8 214',
  'valor': '8214'},
 {'geocod': '1500803',
  'geodsg': 'Aljezur',
  'ind_string': '8 377',
  'valor': '8377'},
 {'geocod': '11C1302',
  'geodsg': 'Baião',
  'ind_string': '8 403',
  'valor': '8403'},
 {'geocod': '11D1815',
  'geodsg': 'São João da Pesqueira',
  'ind_string': '8 509',
  'valor': '8509'},
 {'geocod': '11B1702',
  'geodsg': 'Boticas',
  'ind_string': '8 525',
  'valor': '8525'},
 {'geocod': '1941803',
  'geodsg': 'Castro Daire',
  'ind_string': '8 543',
  'valor': '8543'},
 {'geocod': '1191705',
  'geodsg': 'Mondim de Basto',
  'ind_string': '8 557',
  'valor': '8557'},
 {'geocod': '1500809',
  'geodsg': 'Monchique',
  'ind_string': '8 590',
  'valor': '8590'},
 {'geocod': '11D1711',
  'geodsg': 'Santa Marta de Penaguião',
  'ind_string': '8 600',
  'valor': '8600'},
 {'geocod': '11C0305',
  'geodsg': 'Celorico de Basto',
  'ind_string': '8 657',
  'valor': '8657'},
 {'geocod': '11C1307',
  'geodsg': 'Marco de Canaveses',
  'ind_string': '8 660',
  'valor': '8660'},
 {'geocod': '11D1701',
  'geodsg': 'Alijó',
  'ind_string': '8 726',
  'valor': '8726'},
 {'geocod': '11D1818',
  'geodsg': 'Sernancelhe',
  'ind_string': '8 733',
  'valor': '8733'},
 {'geocod': '11D1820',
  'geodsg': 'Tarouca',
  'ind_string': '8 751',
  'valor': '8751'},
 {'geocod': '3003105',
  'geodsg': 'Ponta do Sol',
  'ind_string': '8 754',
  'valor': '8754'},
 {'geocod': '1190304',
  'geodsg': 'Cabeceiras de Basto',
  'ind_string': '8 795',
  'valor': '8795'},
 {'geocod': '11D1707',
  'geodsg': 'Murça',
  'ind_string': '8 818',
  'valor': '8818'},
 {'geocod': '11D1704',
  'geodsg': 'Mesão Frio',
  'ind_string': '8 820',
  'valor': '8820'},
 {'geocod': '3003102',
  'geodsg': 'Câmara de Lobos',
  'ind_string': '8 826',
  'valor': '8826'},
 {'geocod': '11D0403',
  'geodsg': 'Carrazeda de Ansiães',
  'ind_string': '8 838',
  'valor': '8838'},
 {'geocod': '11D1801',
  'geodsg': 'Armamar',
  'ind_string': '8 869',
  'valor': '8869'},
 {'geocod': '11E0410',
  'geodsg': 'Vila Flor',
  'ind_string': '8 919',
  'valor': '8919'},
 {'geocod': '11C0106',
  'geodsg': 'Castelo de Paiva',
  'ind_string': '8 923',
  'valor': '8923'},
 {'geocod': '11D1807',
  'geodsg': 'Moimenta da Beira',
  'ind_string': '8 948',
  'valor': '8948'},
 {'geocod': '3003107',
  'geodsg': 'Ribeira Brava',
  'ind_string': '9 019',
  'valor': '9019'},
 {'geocod': '11B1706',
  'geodsg': 'Montalegre',
  'ind_string': '9 050',
  'valor': '9050'},
 {'geocod': '1C20210',
  'geodsg': 'Moura',
  'ind_string': '9 051',
  'valor': '9051'},
 {'geocod': '3003101',
  'geodsg': 'Calheta  (R.A.M.)',
  'ind_string': '9 059',
  'valor': '9059'},
 {'geocod': '2004204',
  'geodsg': 'Povoação',
  'ind_string': '9 067',
  'valor': '9067'},
 {'geocod': '1120310',
  'geodsg': 'Terras de Bouro',
  'ind_string': '9 132',
  'valor': '9132'},
 {'geocod': '1C20208',
  'geodsg': 'Ferreira do Alentejo',
  'ind_string': '9 151',
  'valor': '9151'},
 {'geocod': '1190311',
  'geodsg': 'Vieira do Minho',
  'ind_string': '9 162',
  'valor': '9162'},
 {'geocod': '1960905',
  'geodsg': 'Fornos de Algodres',
  'ind_string': '9 162',
  'valor': '9162'},
 {'geocod': '11B1713',
  'geodsg': 'Vila Pouca de Aguiar',
  'ind_string': '9 163',
  'valor': '9163'},
 {'geocod': '1941811',
  'geodsg': 'Penalva do Castelo',
  'ind_string': '9 190',
  'valor': '9190'},
 {'geocod': '11D1812',
  'geodsg': 'Penedono',
  'ind_string': '9 201',
  'valor': '9201'},
 {'geocod': '1960909',
  'geodsg': 'Mêda',
  'ind_string': '9 222',
  'valor': '9222'},
 {'geocod': '11C',
  'geodsg': 'Tâmega e Sousa',
  'ind_string': '9 235',
  'valor': '9235'},
 {'geocod': '1C20213',
  'geodsg': 'Serpa',
  'ind_string': '9 236',
  'valor': '9236'},
 {'geocod': '1941822',
  'geodsg': 'Vila Nova de Paiva',
  'ind_string': '9 251',
  'valor': '9251'},
 {'geocod': '2004202',
  'geodsg': 'Nordeste',
  'ind_string': '9 252',
  'valor': '9252'},
 {'geocod': '11E0412',
  'geodsg': 'Vinhais',
  'ind_string': '9 265',
  'valor': '9265'},
 {'geocod': '1190309',
  'geodsg': 'Póvoa de Lanhoso',
  'ind_string': '9 277',
  'valor': '9277'},
 {'geocod': '1920616',
  'geodsg': 'Tábua',
  'ind_string': '9 334',
  'valor': '9334'},
 {'geocod': '11E0401',
  'geodsg': 'Alfândega da Fé',
  'ind_string': '9 342',
  'valor': '9342'},
 {'geocod': '1111606',
  'geodsg': 'Ponte da Barca',
  'ind_string': '9 347',
  'valor': '9347'},
 {'geocod': '1950505',
  'geodsg': 'Idanha-a-Nova',
  'ind_string': '9 361',
  'valor': '9361'},
 {'geocod': '3003109',
  'geodsg': 'Santana',
  'ind_string': '9 377',
  'valor': '9377'},
 {'geocod': '11C1305',
  'geodsg': 'Lousada',
  'ind_string': '9 399',
  'valor': '9399'},
 {'geocod': '11D1710',
  'geodsg': 'Sabrosa',
  'ind_string': '9 403',
  'valor': '9403'},
 {'geocod': '1950509',
  'geodsg': 'Sertã',
  'ind_string': '9 407',
  'valor': '9407'},
 {'geocod': '1500815',
  'geodsg': 'Vila do Bispo',
  'ind_string': '9 421',
  'valor': '9421'},
 {'geocod': '1931013',
  'geodsg': 'Pedrógão Grande',
  'ind_string': '9 427',
  'valor': '9427'},
 {'geocod': '3003110',
  'geodsg': 'São Vicente',
  'ind_string': '9 455',
  'valor': '9455'},
 {'geocod': '11D0404',
  'geodsg': 'Freixo de Espada à Cinta',
  'ind_string': '9 464',
  'valor': '9464'},
 {'geocod': '1940901',
  'geodsg': 'Aguiar da Beira',
  'ind_string': '9 488',
  'valor': '9488'},
 {'geocod': '11B',
  'geodsg': 'Alto Tâmega e Barroso',
  'ind_string': '9 494',
  'valor': '9494'},
 {'geocod': '11C1303',
  'geodsg': 'Felgueiras',
  'ind_string': '9 494',
  'valor': '9494'},
 {'geocod': '1C20204',
  'geodsg': 'Barrancos',
  'ind_string': '9 512',
  'valor': '9512'},
 {'geocod': '1920611',
  'geodsg': 'Oliveira do Hospital',
  'ind_string': '9 518',
  'valor': '9518'},
 {'geocod': '1C40708',
  'geodsg': 'Mourão',
  'ind_string': '9 535',
  'valor': '9535'},
 {'geocod': '1C40709',
  'geodsg': 'Portel',
  'ind_string': '9 538',
  'valor': '9538'},
 {'geocod': '1111608',
  'geodsg': 'Valença',
  'ind_string': '9 539',
  'valor': '9539'},
 {'geocod': '11C1301',
  'geodsg': 'Amarante',
  'ind_string': '9 539',
  'valor': '9539'},
 {'geocod': '1120313',
  'geodsg': 'Vila Verde',
  'ind_string': '9 555',
  'valor': '9555'},
 {'geocod': '1931007',
  'geodsg': 'Castanheira de Pêra',
  'ind_string': '9 560',
  'valor': '9560'},
 {'geocod': '1111605',
  'geodsg': 'Paredes de Coura',
  'ind_string': '9 562',
  'valor': '9562'},
 {'geocod': '1111601',
  'geodsg': 'Arcos de Valdevez',
  'ind_string': '9 564',
  'valor': '9564'},
 {'geocod': '2004206',
  'geodsg': 'Vila Franca do Campo',
  'ind_string': '9 570',
  'valor': '9570'},
 {'geocod': '1C31211',
  'geodsg': 'Monforte',
  'ind_string': '9 571',
  'valor': '9571'},
 {'geocod': '11C1309',
  'geodsg': 'Paços de Ferreira',
  'ind_string': '9 578',
  'valor': '9578'},
 {'geocod': '1941816',
  'geodsg': 'São Pedro do Sul',
  'ind_string': '9 595',
  'valor': '9595'},
 {'geocod': '1920601',
  'geodsg': 'Arganil',
  'ind_string': '9 612',
  'valor': '9612'},
 {'geocod': '11E0405',
  'geodsg': 'Macedo de Cavaleiros',
  'ind_string': '9 617',
  'valor': '9617'},
 {'geocod': '1931002',
  'geodsg': 'Alvaiázere',
  'ind_string': '9 638',
  'valor': '9638'},
 {'geocod': '2004501',
  'geodsg': 'Calheta (R.A.A.)',
  'ind_string': '9 644',
  'valor': '9644'},
 {'geocod': '1960903',
  'geodsg': 'Celorico da Beira',
  'ind_string': '9 652',
  'valor': '9652'},
 {'geocod': '2004205',
  'geodsg': 'Ribeira Grande',
  'ind_string': '9 660',
  'valor': '9660'},
 {'geocod': '1950507',
  'geodsg': 'Penamacor',
  'ind_string': '9 662',
  'valor': '9662'},
 {'geocod': '1941802',
  'geodsg': 'Carregal do Sal',
  'ind_string': '9 671',
  'valor': '9671'},
 {'geocod': '1941817',
  'geodsg': 'Sátão',
  'ind_string': '9 689',
  'valor': '9689'},
 {'geocod': '3003106',
  'geodsg': 'Porto Moniz',
  'ind_string': '9 698',
  'valor': '9698'},
 {'geocod': '1500816',
  'geodsg': 'Vila Real de Santo António',
  'ind_string': '9 725',
  'valor': '9725'},
 {'geocod': '11A1310',
  'geodsg': 'Paredes',
  'ind_string': '9 727',
  'valor': '9727'},
 {'geocod': '11D1708',
  'geodsg': 'Peso da Régua',
  'ind_string': '9 735',
  'valor': '9735'},
 {'geocod': '1960906',
  'geodsg': 'Gouveia',
  'ind_string': '9 751',
  'valor': '9751'},
 {'geocod': '11E0411',
  'geodsg': 'Vimioso',
  'ind_string': '9 754',
  'valor': '9754'},
 {'geocod': '1931008',
  'geodsg': 'Figueiró dos Vinhos',
  'ind_string': '9 756',
  'valor': '9756'},
 {'geocod': '11A0104',
  'geodsg': 'Arouca',
  'ind_string': '9 769',
  'valor': '9769'},
 {'geocod': '1111603',
  'geodsg': 'Melgaço',
  'ind_string': '9 774',
  'valor': '9774'},
 {'geocod': '11D0914',
  'geodsg': 'Vila Nova de Foz Côa',
  'ind_string': '9 786',
  'valor': '9786'},
 {'geocod': '11C1311',
  'geodsg': 'Penafiel',
  'ind_string': '9 795',
  'valor': '9795'},
 {'geocod': '1960908',
  'geodsg': 'Manteigas',
  'ind_string': '9 804',
  'valor': '9804'},
 {'geocod': '1111604',
  'geodsg': 'Monção',
  'ind_string': '9 806',
  'valor': '9806'},
 {'geocod': '1941824',
  'geodsg': 'Vouzela',
  'ind_string': '9 817',
  'valor': '9817'},
 {'geocod': '1C20214',
  'geodsg': 'Vidigueira',
  'ind_string': '9 872',
  'valor': '9872'},
 {'geocod': '11D0409',
  'geodsg': 'Torre de Moncorvo',
  'ind_string': '9 899',
  'valor': '9899'},
 {'geocod': '1960501',
  'geodsg': 'Belmonte',
  'ind_string': '9 900',
  'valor': '9900'},
 {'geocod': '1C20209',
  'geodsg': 'Mértola',
  'ind_string': '9 906',
  'valor': '9906'},
 {'geocod': '1960904',
  'geodsg': 'Figueira de Castelo Rodrigo',
  'ind_string': '9 921',
  'valor': '9921'},
 {'geocod': '1920606',
  'geodsg': 'Góis',
  'ind_string': '9 948',
  'valor': '9948'},
 {'geocod': '1111607',
  'geodsg': 'Ponte de Lima',
  'ind_string': '9 966',
  'valor': '9966'},
 {'geocod': '1D21411',
  'geodsg': 'Ferreira do Zêzere',
  'ind_string': '9 987',
  'valor': '9987'},
 {'geocod': '1500814',
  'geodsg': 'Tavira',
  'ind_string': '9 988',
  'valor': '9988'},
 {'geocod': '1120301',
  'geodsg': 'Amares',
  'ind_string': '10 008',
  'valor': '10008'},
 {'geocod': '1960913',
  'geodsg': 'Trancoso',
  'ind_string': '10 020',
  'valor': '10020'},
 {'geocod': '1931003',
  'geodsg': 'Ansião',
  'ind_string': '10 038',
  'valor': '10038'},
 {'geocod': '1500807',
  'geodsg': 'Lagos',
  'ind_string': '10 060',
  'valor': '10060'},
 {'geocod': '1960910',
  'geodsg': 'Pinhel',
  'ind_string': '10 062',
  'valor': '10062'},
 {'geocod': '1190307',
  'geodsg': 'Fafe',
  'ind_string': '10 067',
  'valor': '10067'},
 {'geocod': '1500801',
  'geodsg': 'Albufeira',
  'ind_string': '10 069',
  'valor': '10069'},
 {'geocod': '1960912',
  'geodsg': 'Seia',
  'ind_string': '10 099',
  'valor': '10099'},
 {'geocod': '1111610',
  'geodsg': 'Vila Nova de Cerveira',
  'ind_string': '10 115',
  'valor': '10115'},
 {'geocod': '1500813',
  'geodsg': 'Silves',
  'ind_string': '10 122',
  'valor': '10122'},
 {'geocod': '1950510',
  'geodsg': 'Vila de Rei',
  'ind_string': '10 123',
  'valor': '10123'},
 {'geocod': '1C31213',
  'geodsg': 'Ponte de Sor',
  'ind_string': '10 126',
  'valor': '10126'},
 {'geocod': '1920614',
  'geodsg': 'Penela',
  'ind_string': '10 128',
  'valor': '10128'},
 {'geocod': '1920613',
  'geodsg': 'Penacova',
  'ind_string': '10 144',
  'valor': '10144'},
 {'geocod': '11D',
  'geodsg': 'Douro',
  'ind_string': '10 164',
  'valor': '10164'},
 {'geocod': '1C40701',
  'geodsg': 'Alandroal',
  'ind_string': '10 177',
  'valor': '10177'},
 {'geocod': '3003104',
  'geodsg': 'Machico',
  'ind_string': '10 182',
  'valor': '10182'},
 {'geocod': '1920612',
  'geodsg': 'Pampilhosa da Serra',
  'ind_string': '10 188',
  'valor': '10188'},
 {'geocod': '1910112',
  'geodsg': 'Murtosa',
  'ind_string': '10 192',
  'valor': '10192'},
 {'geocod': '1C20207',
  'geodsg': 'Cuba',
  'ind_string': '10 200',
  'valor': '10200'},
 {'geocod': '1941810',
  'geodsg': 'Oliveira de Frades',
  'ind_string': '10 221',
  'valor': '10221'},
 {'geocod': '1C40710',
  'geodsg': 'Redondo',
  'ind_string': '10 232',
  'valor': '10232'},
 {'geocod': '11E0408',
  'geodsg': 'Mogadouro',
  'ind_string': '10 239',
  'valor': '10239'},
 {'geocod': '1120302',
  'geodsg': 'Barcelos',
  'ind_string': '10 246',
  'valor': '10246'},
 {'geocod': '1920617',
  'geodsg': 'Vila Nova de Poiares',
  'ind_string': '10 248',
  'valor': '10248'},
 {'geocod': '1C31215',
  'geodsg': 'Sousel',
  'ind_string': '10 261',
  'valor': '10261'},
 {'geocod': '1D11011',
  'geodsg': 'Nazaré',
  'ind_string': '10 263',
  'valor': '10263'},
 {'geocod': '1941814',
  'geodsg': 'Santa Comba Dão',
  'ind_string': '10 289',
  'valor': '10289'},
 {'geocod': '11E0407',
  'geodsg': 'Mirandela',
  'ind_string': '10 316',
  'valor': '10316'},
 {'geocod': '2004601',
  'geodsg': 'Lajes do Pico',
  'ind_string': '10 339',
  'valor': '10339'},
 {'geocod': '1941806',
  'geodsg': 'Mangualde',
  'ind_string': '10 372',
  'valor': '10372'},
 {'geocod': '1D31407',
  'geodsg': 'Chamusca',
  'ind_string': '10 373',
  'valor': '10373'},
 {'geocod': '1C40703',
  'geodsg': 'Borba',
  'ind_string': '10 389',
  'valor': '10389'},
 {'geocod': '1190314',
  'geodsg': 'Vizela',
  'ind_string': '10 406',
  'valor': '10406'},
 {'geocod': '1500810',
  'geodsg': 'Olhão',
  'ind_string': '10 415',
  'valor': '10415'},
 {'geocod': '1B01506',
  'geodsg': 'Moita',
  'ind_string': '10 419',
  'valor': '10419'},
 {'geocod': '1941821',
  'geodsg': 'Tondela',
  'ind_string': '10 421',
  'valor': '10421'},
 {'geocod': '1500806',
  'geodsg': 'Lagoa',
  'ind_string': '10 434',
  'valor': '10434'},
 {'geocod': '11E',
  'geodsg': 'Terras de Trás-os-Montes',
  'ind_string': '10 455',
  'valor': '10455'},
 {'geocod': '1921808',
  'geodsg': 'Mortágua',
  'ind_string': '10 465',
  'valor': '10465'},
 {'geocod': '1950508',
  'geodsg': 'Proença-a-Nova',
  'ind_string': '10 466',
  'valor': '10466'},
 {'geocod': '1910118',
  'geodsg': 'Vagos',
  'ind_string': '10 467',
  'valor': '10467'},
 {'geocod': '1D21402',
  'geodsg': 'Alcanena',
  'ind_string': '10 477',
  'valor': '10477'},
 {'geocod': '11D1805',
  'geodsg': 'Lamego',
  'ind_string': '10 520',
  'valor': '10520'},
 {'geocod': '1C31210',
  'geodsg': 'Marvão',
  'ind_string': '10 521',
  'valor': '10521'},
 {'geocod': '1960911',
  'geodsg': 'Sabugal',
  'ind_string': '10 545',
  'valor': '10545'},
 {'geocod': '1960504',
  'geodsg': 'Fundão',
  'ind_string': '10 547',
  'valor': '10547'},
 {'geocod': '11B1703',
  'geodsg': 'Chaves',
  'ind_string': '10 552',
  'valor': '10552'},
 {'geocod': '1D31414',
  'geodsg': 'Rio Maior',
  'ind_string': '10 553',
  'valor': '10553'},
 {'geocod': '1500811',
  'geodsg': 'Portimão',
  'ind_string': '10 576',
  'valor': '10576'},
 {'geocod': '1500804',
  'geodsg': 'Castro Marim',
  'ind_string': '10 578',
  'valor': '10578'},
 {'geocod': '1D11014',
  'geodsg': 'Peniche',
  'ind_string': '10 584',
  'valor': '10584'},
 {'geocod': '1941809',
  'geodsg': 'Nelas',
  'ind_string': '10 590',
  'valor': '10590'},
 {'geocod': '1C31203',
  'geodsg': 'Avis',
  'ind_string': '10 620',
  'valor': '10620'},
 {'geocod': '1931015',
  'geodsg': 'Pombal',
  'ind_string': '10 629',
  'valor': '10629'},
 {'geocod': '1500802',
  'geodsg': 'Alcoutim',
  'ind_string': '10 649',
  'valor': '10649'},
 {'geocod': '15',
  'geodsg': 'Algarve',
  'ind_string': '10 658',
  'valor': '10658'},
 {'geocod': '150',
  'geodsg': 'Algarve',
  'ind_string': '10 658',
  'valor': '10658'},
 {'geocod': '1920609',
  'geodsg': 'Miranda do Corvo',
  'ind_string': '10 658',
  'valor': '10658'},
 {'geocod': '1C20212',
  'geodsg': 'Ourique',
  'ind_string': '10 675',
  'valor': '10675'},
 {'geocod': '1D11005',
  'geodsg': 'Bombarral',
  'ind_string': '10 683',
  'valor': '10683'},
 {'geocod': '111',
  'geodsg': 'Alto Minho',
  'ind_string': '10 702',
  'valor': '10702'},
 {'geocod': '1950506',
  'geodsg': 'Oleiros',
  'ind_string': '10 710',
  'valor': '10710'},
 {'geocod': '1C40711',
  'geodsg': 'Reguengos de Monsaraz',
  'ind_string': '10 742',
  'valor': '10742'},
 {'geocod': '1910114',
  'geodsg': 'Oliveira do Bairro',
  'ind_string': '10 746',
  'valor': '10746'},
 {'geocod': '1D31404',
  'geodsg': 'Alpiarça',
  'ind_string': '10 757',
  'valor': '10757'},
 {'geocod': '1500808',
  'geodsg': 'Loulé',
  'ind_string': '10 762',
  'valor': '10762'},
 {'geocod': '1C31207',
  'geodsg': 'Elvas',
  'ind_string': '10 771',
  'valor': '10771'},
 {'geocod': '1D21413',
  'geodsg': 'Mação',
  'ind_string': '10 773',
  'valor': '10773'},
 {'geocod': '1C31209',
  'geodsg': 'Gavião',
  'ind_string': '10 781',
  'valor': '10781'},
 {'geocod': '1C20203',
  'geodsg': 'Alvito',
  'ind_string': '10 794',
  'valor': '10794'},
 {'geocod': '1D31403',
  'geodsg': 'Almeirim',
  'ind_string': '10 800',
  'valor': '10800'},
 {'geocod': '1C2',
  'geodsg': 'Baixo Alentejo',
  'ind_string': '10 805',
  'valor': '10805'},
 {'geocod': '1920608',
  'geodsg': 'Mira',
  'ind_string': '10 814',
  'valor': '10814'},
 {'geocod': '1D21417',
  'geodsg': 'Sardoal',
  'ind_string': '10 833',
  'valor': '10833'},
 {'geocod': '1910117',
  'geodsg': 'Sever do Vouga',
  'ind_string': '10 841',
  'valor': '10841'},
 {'geocod': '196',
  'geodsg': 'Beiras e Serra da Estrela',
  'ind_string': '10 846',
  'valor': '10846'},
 {'geocod': '194',
  'geodsg': 'Viseu Dão Lafões',
  'ind_string': '10 900',
  'valor': '10900'},
 {'geocod': '1D21421',
  'geodsg': 'Ourém',
  'ind_string': '10 902',
  'valor': '10902'},
 {'geocod': '1C31206',
  'geodsg': 'Crato',
  'ind_string': '10 906',
  'valor': '10906'},
 {'geocod': '2004401',
  'geodsg': 'Santa Cruz da Graciosa',
  'ind_string': '10 911',
  'valor': '10911'},
 {'geocod': '1920602',
  'geodsg': 'Cantanhede',
  'ind_string': '10 916',
  'valor': '10916'},
 {'geocod': '119', 'geodsg': 'Ave', 'ind_string': '10 919', 'valor': '10919'},
 {'geocod': '1C11501',
  'geodsg': 'Alcácer do Sal',
  'ind_string': '10 920',
  'valor': '10920'},
 {'geocod': '1D31409',
  'geodsg': 'Coruche',
  'ind_string': '10 948',
  'valor': '10948'},
 {'geocod': '1D11108',
  'geodsg': 'Lourinhã',
  'ind_string': '10 967',
  'valor': '10967'},
 {'geocod': '1C1',
  'geodsg': 'Alentejo Litoral',
  'ind_string': '10 991',
  'valor': '10991'},
 {'geocod': '1D11001',
  'geodsg': 'Alcobaça',
  'ind_string': '11 005',
  'valor': '11005'},
 {'geocod': '11E0406',
  'geodsg': 'Miranda do Douro',
  'ind_string': '11 011',
  'valor': '11011'},
 {'geocod': '1C31201',
  'geodsg': 'Alter do Chão',
  'ind_string': '11 019',
  'valor': '11019'},
 {'geocod': '1C40713',
  'geodsg': 'Viana do Alentejo',
  'ind_string': '11 035',
  'valor': '11035'},
 {'geocod': '195',
  'geodsg': 'Beira Baixa',
  'ind_string': '11 044',
  'valor': '11044'},
 {'geocod': '1960503',
  'geodsg': 'Covilhã',
  'ind_string': '11 090',
  'valor': '11090'},
 {'geocod': '1D11104',
  'geodsg': 'Cadaval',
  'ind_string': '11 099',
  'valor': '11099'},
 {'geocod': '1931016',
  'geodsg': 'Porto de Mós',
  'ind_string': '11 118',
  'valor': '11118'},
 {'geocod': '1920607',
  'geodsg': 'Lousã',
  'ind_string': '11 126',
  'valor': '11126'},
 {'geocod': '1500812',
  'geodsg': 'São Brás de Alportel',
  'ind_string': '11 185',
  'valor': '11185'},
 {'geocod': '1190308',
  'geodsg': 'Guimarães',
  'ind_string': '11 188',
  'valor': '11188'},
 {'geocod': '1C3',
  'geodsg': 'Alto Alentejo',
  'ind_string': '11 194',
  'valor': '11194'},
 {'geocod': '1C31202',
  'geodsg': 'Arronches',
  'ind_string': '11 197',
  'valor': '11197'},
 {'geocod': '1C31208',
  'geodsg': 'Fronteira',

In [45]:
income_inhabitant_df = pd.DataFrame(data)
income_inhabitant_df.head(5)

    geocod    geodsg ind_string valor
0  11C1804   Cinfães      7 696  7696
1  11C1813   Resende      7 839  7839
2  1C10211   Odemira      7 958  7958
3  11B1712  Valpaços      8 100  8100
4  11D1819   Tabuaço      8 191  8191

In [46]:
income_inhabitant_df = income_inhabitant_df.rename(columns={"valor": "income"})
income_inhabitant_df = income_inhabitant_df.drop(columns=['ind_string'])

In [47]:
income_inhabitant_df.shape

(347, 3)

In [48]:
income_inhabitant_df.dtypes

geocod    object
geodsg    object
income    object
dtype: object

In [49]:
income_inhabitant_df.describe()

         geocod                      geodsg income
count       347                         347    347
unique      347                         340    331
top     1A01110  Região Autónoma da Madeira  10658
freq          1                           3      3

In [50]:
income_inhabitant_df.isna().sum()

geocod    0
geodsg    0
income    0
dtype: int64

In [51]:
income_inhabitant_df.duplicated().sum()

np.int64(0)

In [56]:
(income_inhabitant_df.dropna(subset=['geodsg'])
 .drop_duplicates(subset=['geodsg'])
 .assign(normalized = income_inhabitant_df['geodsg'].astype('string').str.strip().str.lower())
 .groupby('normalized')['geodsg']
 .nunique()
 ).max()

np.int64(1)

In [60]:
income_inhabitant_df.groupby('geocod')['geodsg'].nunique().max()

np.int64(1)

In [61]:
income_inhabitant_df.groupby('geodsg')['geocod'].nunique().max()

np.int64(3)

In [62]:
check = (
    income_inhabitant_df
    .groupby('geodsg')['geocod']
    .nunique()
)

check[check > 1]

conflict_names = check[check > 1].index

income_inhabitant_df[
    income_inhabitant_df['geodsg'].isin(conflict_names)
][['geodsg', 'geocod']].drop_duplicates()

                         geodsg geocod
165                     Algarve     15
166                     Algarve    150
262  Região Autónoma da Madeira      3
263  Região Autónoma da Madeira     30
264  Região Autónoma da Madeira    300
286  Região Autónoma dos Açores      2
287  Região Autónoma dos Açores     20
288  Região Autónoma dos Açores    200
308        Península de Setúbal     1B
309        Península de Setúbal    1B0
336               Grande Lisboa     1A
337               Grande Lisboa    1A0

In [52]:
income_inhabitant_df.to_csv(r"../data_raw/income_inhabitant.csv", encoding='utf-8', index=False)

## Observaciones sobre el dataset 'income_inhabitant':

Se ha convertido el dataset de JSON a CSV para facilitar su carga posterior.
Tras los cambios necesarios a nivel de formato del dataset, se ha llevado a cabo la revisión del mismo.

Las unidades indicadas en los metadatos son correctas.
El dataset se compone de 347 registros y 4 variables reducidas a 3 para evitar redundancia.

No se observan valores numéricos extremos.

En cuanto al tipo de datos de las variables, se debería convertir a string tanto 'geocod' como 'geodsg'. 'income' debería ser numérica.

No se observan duplicados. Los nombres de cada zona geográfica mantienen un mismo formato.

Para cada 'geocod' se observa un solo 'geodsg', lo cual es correcto.
Para cada 'geodsg' puede haber más de un 'geocod' si bien se comprueba que se trata de distintos niveles de clasificación geográfica para una misma región, por lo que es correcto.

En cuanto a los códigos: 'geocod' es un código jerárquico NUTS cuya longitud indica el nivel geográfico. En los concelhos (7 caracteres) está formado por NUTS III (3) + código de concelho DICO (4), el mismo código que usa E-REDES. En la limpieza se extrae como 'cod_concelho'. Estas comprobaciones de nombres validan la fuente; los nombres definitivos de cada nivel se asignarán desde la tabla de referencia geográfica ('app/utils/concelho_codes/') a partir de 'cod_concelho'.

## **land_use_variation_0014800**: Rate of surface variation (% - COS - Series 2) of territorial units by Geographic localization (NUTS - 2024) and Surface by land use and cover

CHECK SOURCE

## **pop_density_0013189**: Population's density (No./ km²) by Place of residence (NUTS - 2024)

In [66]:
with open(r"../data_raw/pop_density_0013189.json", "r", encoding='utf-8') as file:
    data = json.load(file)

data = data[0]['Dados']['2025']

pop_density_df = pd.DataFrame(data)
pop_density_df.head(5)

    geocod         geodsg ind_string valor
0  1500802       Alcoutim        4,3   4.3
1  1C20209        Mértola        4,6   4.6
2  1950505  Idanha-a-Nova        5,9   5.9
3  1C31203           Avis        6,0     6
4  1C31211       Monforte        6,8   6.8

In [67]:
pop_density_df = pop_density_df.drop(columns=['ind_string'])
pop_density_df = pop_density_df.rename(columns={'valor': 'density'})
pop_density_df.head(2)

    geocod    geodsg density
0  1500802  Alcoutim     4.3
1  1C20209   Mértola     4.6

In [68]:
pop_density_df.shape

(347, 3)

In [69]:
pop_density_df.dtypes

geocod     object
geodsg     object
density    object
dtype: object

In [70]:
pop_density_df.describe()

         geocod                      geodsg density
count       347                         347     347
unique      347                         340     316
top     1A01115  Região Autónoma dos Açores     7.7
freq          1                           3       3

In [71]:
pop_density_df.isna().sum()

geocod     0
geodsg     0
density    0
dtype: int64

In [72]:
pop_density_df.duplicated().sum()

np.int64(0)

In [73]:
(pop_density_df.dropna(subset=['geodsg'])
 .drop_duplicates(subset=['geodsg'])
 .assign(normalized = pop_density_df['geodsg'].astype('string').str.strip().str.lower())
 .groupby('normalized')['geodsg']
 .nunique()
).max()

np.int64(1)

In [74]:
pop_density_df.groupby('geocod')['geodsg'].nunique().max()

np.int64(1)

In [75]:
pop_density_df.groupby('geodsg')['geocod'].nunique().max()

np.int64(3)

In [ ]:
check = pop_density_df.groupby('geodsg')['geocod'].nunique()

conflict_names = check[check > 1].index # Al haber agrupado por geodsg, pasa a ser el index

pop_density_df[pop_density_df['geodsg'].isin(conflict_names)]

    geocod                      geodsg density
204      2  Região Autónoma dos Açores   105.7
205     20  Região Autónoma dos Açores   105.7
206    200  Região Autónoma dos Açores   105.7
213     15                     Algarve   115.7
214    150                     Algarve   115.7
287      3  Região Autónoma da Madeira   332.2
288     30  Região Autónoma da Madeira   332.2
289    300  Região Autónoma da Madeira   332.2
310     1B        Península de Setúbal   576.9
311    1B0        Península de Setúbal   576.9
332     1A               Grande Lisboa  1737.6
333    1A0               Grande Lisboa  1737.6

In [83]:
pop_density_df.to_csv(r"../data_raw/pop_density.csv", encoding='utf-8', index=False)

## Observaciones sobre el dataset 'pop_density':

Se ha convertido el dataset de JSON a CSV para facilitar su carga posterior.
Tras los cambios necesarios a nivel de formato del dataset, se ha llevado a cabo la revisión del mismo.

Las unidades indicadas en los metadatos son correctas.
El dataset se compone de 347 registros y 4 variables reducidas a 3 para evitar redundancia.

No se observan valores numéricos extremos.

En cuanto al tipo de datos de las variables, se debería convertir a string tanto 'geocod' como 'geodsg'. 'density' debería ser numérica.

No se observan duplicados. Los nombres de cada zona geográfica mantienen un mismo formato.

Para cada 'geocod' se observa un solo 'geodsg', lo cual es correcto.
Para cada 'geodsg' puede haber más de un 'geocod' si bien se comprueba que se trata de distintos niveles de clasificación geográfica para una misma región, por lo que es correcto. Misma situación que el caso anterior.

En ambos casos, las islas quedarán fuera del análisis, puesto que solo se cubrirá la parte continental.

En cuanto a los códigos: 'geocod' es un código jerárquico NUTS cuya longitud indica el nivel geográfico. En los concelhos (7 caracteres) está formado por NUTS III (3) + código de concelho DICO (4), el mismo código que usa E-REDES. En la limpieza se extrae como 'cod_concelho'. Estas comprobaciones de nombres validan la fuente; los nombres definitivos de cada nivel se asignarán desde la tabla de referencia geográfica ('app/utils/concelho_codes/') a partir de 'cod_concelho'.